/**
 * Nationwide list of German cities used to populate the location step of the
 * project planner. Kept as a flat string array so it can be reused for both the
 * seed `locationOptions` and any other place that needs a city list.
 *
 * Covers every Großstadt (>100k inhabitants) plus a broad set of mid-sized
 * towns, with extra coverage around the company's home region (Bayerisch-
 * Schwaben / Ulm). Combined with the autocomplete field, the user can quickly
 * type-to-find their town; a free-text entry is still allowed for anything not
 * listed.
 */
export const germanCities: string[] = [
  "Aachen",
  "Aalen",
  "Augsburg",
  "Bad Homburg",
  "Bamberg",
  "Bayreuth",
  "Berlin",
  "Bergisch Gladbach",
  "Bielefeld",
  "Bocholt",
  "Bochum",
  "Bonn",
  "Bottrop",
  "Brandenburg an der Havel",
  "Braunschweig",
  "Bremen",
  "Bremerhaven",
  "Chemnitz",
  "Cottbus",
  "Darmstadt",
  "Dessau-Roßlau",
  "Dillingen an der Donau",
  "Dortmund",
  "Dresden",
  "Duisburg",
  "Düren",
  "Düsseldorf",
  "Erfurt",
  "Erlangen",
  "Esslingen am Neckar",
  "Flensburg",
  "Frankfurt am Main",
  "Freiburg im Breisgau",
  "Friedrichshafen",
  "Fürth",
  "Gelsenkirchen",
  "Gera",
  "Gießen",
  "Göppingen",
  "Görlitz",
  "Göttingen",
  "Günzburg",
  "Gütersloh",
  "Hagen",
  "Halle (Saale)",
  "Hamburg",
  "Hamm",
  "Hanau",
  "Hannover",
  "Heidelberg",
  "Heidenheim an der Brenz",
  "Heilbronn",
  "Herne",
  "Hildesheim",
  "Illertissen",
  "Ingolstadt",
  "Iserlohn",
  "Jena",
  "Kaiserslautern",
  "Karlsruhe",
  "Kassel",
  "Kaufbeuren",
  "Kempten (Allgäu)",
  "Kiel",
  "Koblenz",
  "Köln",
  "Konstanz",
  "Krefeld",
  "Landshut",
  "Leipzig",
  "Leverkusen",
  "Lindau (Bodensee)",
  "Lübeck",
  "Ludwigsburg",
  "Ludwigshafen am Rhein",
  "Lünen",
  "Magdeburg",
  "Mainz",
  "Mannheim",
  "Marburg",
  "Memmingen",
  "Mindelheim",
  "Mönchengladbach",
  "Mülheim an der Ruhr",
  "München",
  "Münster",
  "Neu-Ulm",
  "Neubrandenburg",
  "Neuburg an der Donau",
  "Neuss",
  "Neustadt an der Weinstraße",
  "Nördlingen",
  "Nürnberg",
  "Oberhausen",
  "Offenbach am Main",
  "Offenburg",
  "Oldenburg",
  "Osnabrück",
  "Paderborn",
  "Passau",
  "Pforzheim",
  "Potsdam",
  "Recklinghausen",
  "Regensburg",
  "Remscheid",
  "Reutlingen",
  "Rosenheim",
  "Rostock",
  "Saarbrücken",
  "Salzgitter",
  "Schweinfurt",
  "Schwäbisch Gmünd",
  "Senden",
  "Siegen",
  "Sindelfingen",
  "Solingen",
  "Stuttgart",
  "Trier",
  "Tübingen",
  "Ulm",
  "Villingen-Schwenningen",
  "Weiden in der Oberpfalz",
  "Weingarten",
  "Wiesbaden",
  "Wolfsburg",
  "Worms",
  "Wuppertal",
  "Würzburg",
  "Zwickau",
];
